/** Mirrors `scoring::catalog::all_roles` — keep labels in sync with catalog.rs. */
export const ROLE_CATALOG = [
  { id: "goalkeeper_ip", label: "Goalkeeper (IP)" },
  { id: "ball_playing_goalkeeper_ip", label: "Ball-Playing Goalkeeper (IP)" },
  { id: "no_nonsense_goalkeeper_ip", label: "No-Nonsense Goalkeeper (IP)" },
  { id: "line_holding_keeper_oop", label: "Line-Holding Keeper (OOP)" },
  { id: "sweeper_keeper_oop", label: "Sweeper Keeper (OOP)" },
  { id: "centre_back_ip", label: "Centre-Back (IP)" },
  { id: "ball_playing_centre_back_ip", label: "Ball-Playing Centre-Back (IP)" },
  { id: "no_nonsense_centre_back_ip", label: "No-Nonsense Centre-Back (IP)" },
  { id: "wide_centre_back_ip", label: "Wide Centre-Back (IP)" },
  { id: "advanced_centre_back_ip", label: "Advanced Centre-Back (IP)" },
  { id: "overlapping_centre_back_ip", label: "Overlapping Centre-Back (IP)" },
  { id: "covering_centre_back_oop", label: "Covering Centre-Back (OOP)" },
  { id: "stopping_centre_back_oop", label: "Stopping Centre-Back (OOP)" },
  {
    id: "covering_wide_centre_back_oop",
    label: "Covering Wide Centre-Back (OOP)",
  },
  {
    id: "stopping_wide_centre_back_oop",
    label: "Stopping Wide Centre-Back (OOP)",
  },
  { id: "full_back_ip", label: "Full-Back (IP)" },
  { id: "inside_full_back_ip", label: "Inside Full-Back (IP)" },
  { id: "holding_full_back_oop", label: "Holding Full-Back (OOP)" },
  { id: "pressing_full_back_oop", label: "Pressing Full-Back (OOP)" },
  { id: "inside_wing_back_ip", label: "Inside Wing-Back (IP)" },
  { id: "playmaking_wing_back_ip", label: "Playmaking Wing-Back (IP)" },
  { id: "wing_back_ip", label: "Wing-Back (IP)" },
  { id: "advanced_wing_back_ip", label: "Advanced Wing-Back (IP)" },
  { id: "holding_wing_back_oop", label: "Holding Wing-Back (OOP)" },
  { id: "pressing_wing_back_oop", label: "Pressing Wing-Back (OOP)" },
  { id: "defensive_midfielder_ip", label: "Defensive Midfielder (IP)" },
  { id: "box_to_box_midfielder_ip", label: "Box-to-Box Midfielder (IP)" },
  { id: "box_to_box_playmaker_ip", label: "Box-to-Box Playmaker (IP)" },
  { id: "deep_lying_playmaker_ip", label: "Deep-Lying Playmaker (IP)" },
  { id: "half_back_ip", label: "Half-Back (IP)" },
  {
    id: "dropping_defensive_midfielder_oop",
    label: "Dropping Defensive Midfielder (OOP)",
  },
  {
    id: "pressing_defensive_midfielder_oop",
    label: "Pressing Defensive Midfielder (OOP)",
  },
  {
    id: "screening_defensive_midfielder_oop",
    label: "Screening Defensive Midfielder (OOP)",
  },
  {
    id: "wide_covering_defensive_midfielder_oop",
    label: "Wide Covering Defensive Midfielder (OOP)",
  },
  { id: "central_midfielder_ip", label: "Central Midfielder (IP)" },
  { id: "advanced_playmaker_ip", label: "Advanced Playmaker (IP)" },
  { id: "midfield_playmaker_ip", label: "Midfield Playmaker (IP)" },
  { id: "wide_central_midfielder_ip", label: "Wide Central Midfielder (IP)" },
  {
    id: "pressing_central_midfielder_oop",
    label: "Pressing Central Midfielder (OOP)",
  },
  {
    id: "screening_central_midfielder_oop",
    label: "Screening Central Midfielder (OOP)",
  },
  {
    id: "wide_covering_central_midfielder_oop",
    label: "Wide Covering Central Midfielder (OOP)",
  },
  { id: "wide_midfielder_ip", label: "Wide Midfielder (IP)" },
  {
    id: "tracking_wide_midfielder_oop",
    label: "Tracking Wide Midfielder (OOP)",
  },
  {
    id: "wide_outlet_wide_midfielder_oop",
    label: "Wide Outlet Wide Midfielder (OOP)",
  },
  { id: "inside_winger_ip", label: "Inside Winger (IP)" },
  { id: "playmaking_winger_ip", label: "Playmaking Winger (IP)" },
  { id: "winger_ip", label: "Winger (IP)" },
  { id: "attacking_midfielder_ip", label: "Attacking Midfielder (IP)" },
  { id: "channel_midfielder_ip", label: "Channel Midfielder (IP)" },
  { id: "free_role_ip", label: "Free Role (IP)" },
  { id: "second_striker_ip", label: "Second Striker (IP)" },
  {
    id: "central_outlet_attacking_midfielder_oop",
    label: "Central Outlet Attacking Midfielder (OOP)",
  },
  {
    id: "splitting_outlet_attacking_midfielder_oop",
    label: "Splitting Outlet Attacking Midfielder (OOP)",
  },
  {
    id: "tracking_attacking_midfielder_oop",
    label: "Tracking Attacking Midfielder (OOP)",
  },
  { id: "wide_forward_ip", label: "Wide Forward (IP)" },
  { id: "inside_forward_ip", label: "Inside Forward (IP)" },
  { id: "inside_outlet_winger_oop", label: "Inside Outlet Winger (OOP)" },
  { id: "tracking_winger_oop", label: "Tracking Winger (OOP)" },
  { id: "wide_outlet_winger_oop", label: "Wide Outlet Winger (OOP)" },
  { id: "centre_forward_ip", label: "Centre Forward (IP)" },
  { id: "channel_forward_ip", label: "Channel Forward (IP)" },
  { id: "deep_lying_forward_ip", label: "Deep-Lying Forward (IP)" },
  { id: "false_nine_ip", label: "False Nine (IP)" },
  { id: "poacher_ip", label: "Poacher (IP)" },
  { id: "target_forward_ip", label: "Target Forward (IP)" },
  {
    id: "central_outlet_centre_forward_oop",
    label: "Central Outlet Centre Forward (OOP)",
  },
  {
    id: "splitting_outlet_centre_forward_oop",
    label: "Splitting Outlet Centre Forward (OOP)",
  },
  { id: "tracking_centre_forward_oop", label: "Tracking Centre Forward (OOP)" },
] as const;
