import { orderedPositions } from "./position-order";

export type MoneyballRolePhase = "in_possession" | "out_of_possession";

export type MoneyballRolePositionFamily =
  | "attacking_midfielder"
  | "central_defender"
  | "central_midfielder"
  | "defensive_midfielder"
  | "full_back"
  | "goalkeeper"
  | "striker"
  | "wide_midfielder"
  | "wing_back"
  | "winger";

export type MoneyballRoleCatalogEntry = {
  id: string;
  label: string;
  phase: MoneyballRolePhase;
  positionFamily: MoneyballRolePositionFamily;
  positionTags: readonly string[];
};

export const MONEYBALL_ROLE_CATALOG_VERSION = 1 as const;

const role = (
  id: string,
  displayName: string,
  phase: MoneyballRolePhase,
  positionFamily: MoneyballRolePositionFamily,
  positionTags: readonly string[],
): MoneyballRoleCatalogEntry => ({
  id,
  label: `${displayName} (${phase === "in_possession" ? "IP" : "OOP"} · ${orderedPositions(positionTags).join("/")})`,
  phase,
  positionFamily,
  positionTags,
});

export const MONEYBALL_ROLE_CATALOG = [
  role(
    "amc_attacking_midfielder_ip",
    "Attacking Midfielder",
    "in_possession",
    "attacking_midfielder",
    ["AMC"],
  ),
  role(
    "amc_advanced_playmaker_ip",
    "Advanced Playmaker",
    "in_possession",
    "attacking_midfielder",
    ["AMC"],
  ),
  role(
    "amc_free_role_ip",
    "Free Role",
    "in_possession",
    "attacking_midfielder",
    ["AMC"],
  ),
  role(
    "amc_second_striker_ip",
    "Second Striker",
    "in_possession",
    "attacking_midfielder",
    ["AMC"],
  ),
  role(
    "amc_channel_midfielder_ip",
    "Channel Midfielder",
    "in_possession",
    "attacking_midfielder",
    ["AMC"],
  ),
  role(
    "amc_attacking_midfielder_oop",
    "Attacking Midfielder",
    "out_of_possession",
    "attacking_midfielder",
    ["AMC"],
  ),
  role(
    "amc_tracking_attacking_midfielder_oop",
    "Tracking Attacking Midfielder",
    "out_of_possession",
    "attacking_midfielder",
    ["AMC"],
  ),
  role(
    "amc_central_outlet_attacking_midfielder_oop",
    "Central Outlet Attacking Midfielder",
    "out_of_possession",
    "attacking_midfielder",
    ["AMC"],
  ),
  role(
    "amc_splitting_outlet_attacking_midfielder_oop",
    "Splitting Outlet Attacking Midfielder",
    "out_of_possession",
    "attacking_midfielder",
    ["AMC"],
  ),
  role(
    "dc_centre_back_ip",
    "Centre-Back",
    "in_possession",
    "central_defender",
    ["DC"],
  ),
  role(
    "dc_advanced_centre_back_ip",
    "Advanced Centre-Back",
    "in_possession",
    "central_defender",
    ["DC"],
  ),
  role(
    "dc_ball_playing_centre_back_ip",
    "Ball-Playing Centre-Back",
    "in_possession",
    "central_defender",
    ["DC"],
  ),
  role(
    "dc_no_nonsense_centre_back_ip",
    "No-Nonsense Centre-Back",
    "in_possession",
    "central_defender",
    ["DC"],
  ),
  role(
    "dc_wide_centre_back_ip",
    "Wide Centre-Back",
    "in_possession",
    "central_defender",
    ["DC"],
  ),
  role(
    "dc_overlapping_centre_back_ip",
    "Overlapping Centre-Back",
    "in_possession",
    "central_defender",
    ["DC"],
  ),
  role(
    "dc_centre_back_oop",
    "Centre-Back",
    "out_of_possession",
    "central_defender",
    ["DC"],
  ),
  role(
    "dc_stopping_centre_back_oop",
    "Stopping Centre-Back",
    "out_of_possession",
    "central_defender",
    ["DC"],
  ),
  role(
    "dc_covering_centre_back_oop",
    "Covering Centre-Back",
    "out_of_possession",
    "central_defender",
    ["DC"],
  ),
  role(
    "dc_wide_centre_back_oop",
    "Wide Centre-Back",
    "out_of_possession",
    "central_defender",
    ["DC"],
  ),
  role(
    "dc_wide_stopping_centre_back_oop",
    "Wide Stopping Centre-Back",
    "out_of_possession",
    "central_defender",
    ["DC"],
  ),
  role(
    "dc_wide_covering_centre_back_oop",
    "Wide Covering Centre-Back",
    "out_of_possession",
    "central_defender",
    ["DC"],
  ),
  role(
    "mc_central_midfielder_ip",
    "Central Midfielder",
    "in_possession",
    "central_midfielder",
    ["MC"],
  ),
  role(
    "mc_attacking_midfielder_ip",
    "Attacking Midfielder",
    "in_possession",
    "central_midfielder",
    ["MC"],
  ),
  role(
    "mc_advanced_playmaker_ip",
    "Advanced Playmaker",
    "in_possession",
    "central_midfielder",
    ["MC"],
  ),
  role(
    "mc_wide_central_midfielder_ip",
    "Wide Central Midfielder",
    "in_possession",
    "central_midfielder",
    ["MC"],
  ),
  role(
    "mc_channel_midfielder_ip",
    "Channel Midfielder",
    "in_possession",
    "central_midfielder",
    ["MC"],
  ),
  role(
    "mc_midfield_playmaker_ip",
    "Midfield Playmaker",
    "in_possession",
    "central_midfielder",
    ["MC"],
  ),
  role(
    "mc_central_midfielder_oop",
    "Central Midfielder",
    "out_of_possession",
    "central_midfielder",
    ["MC"],
  ),
  role(
    "mc_pressing_central_midfielder_oop",
    "Pressing Central Midfielder",
    "out_of_possession",
    "central_midfielder",
    ["MC"],
  ),
  role(
    "mc_screening_central_midfielder_oop",
    "Screening Central Midfielder",
    "out_of_possession",
    "central_midfielder",
    ["MC"],
  ),
  role(
    "mc_wide_covering_central_midfielder_oop",
    "Wide Covering Central Midfielder",
    "out_of_possession",
    "central_midfielder",
    ["MC"],
  ),
  role(
    "dm_defensive_midfielder_ip",
    "Defensive Midfielder",
    "in_possession",
    "defensive_midfielder",
    ["DM"],
  ),
  role(
    "dm_deep_lying_playmaker_ip",
    "Deep-Lying Playmaker",
    "in_possession",
    "defensive_midfielder",
    ["DM"],
  ),
  role(
    "dm_box_to_box_midfielder_ip",
    "Box-to-Box Midfielder",
    "in_possession",
    "defensive_midfielder",
    ["DM"],
  ),
  role(
    "dm_half_back_ip",
    "Half-Back",
    "in_possession",
    "defensive_midfielder",
    ["DM"],
  ),
  role(
    "dm_box_to_box_playmaker_ip",
    "Box-to-Box Playmaker",
    "in_possession",
    "defensive_midfielder",
    ["DM"],
  ),
  role(
    "dm_defensive_midfielder_oop",
    "Defensive Midfielder",
    "out_of_possession",
    "defensive_midfielder",
    ["DM"],
  ),
  role(
    "dm_dropping_defensive_midfielder_oop",
    "Dropping Defensive Midfielder",
    "out_of_possession",
    "defensive_midfielder",
    ["DM"],
  ),
  role(
    "dm_pressing_defensive_midfielder_oop",
    "Pressing Defensive Midfielder",
    "out_of_possession",
    "defensive_midfielder",
    ["DM"],
  ),
  role(
    "dm_screening_defensive_midfielder_oop",
    "Screening Defensive Midfielder",
    "out_of_possession",
    "defensive_midfielder",
    ["DM"],
  ),
  role(
    "dm_wide_covering_defensive_midfielder_oop",
    "Wide Covering Defensive Midfielder",
    "out_of_possession",
    "defensive_midfielder",
    ["DM"],
  ),
  role("dl_dr_full_back_ip", "Full-Back", "in_possession", "full_back", [
    "DL",
    "DR",
  ]),
  role("dl_dr_wing_back_ip", "Wing-Back", "in_possession", "full_back", [
    "DL",
    "DR",
  ]),
  role(
    "dl_dr_inside_wing_back_ip",
    "Inside Wing-Back",
    "in_possession",
    "full_back",
    ["DL", "DR"],
  ),
  role(
    "dl_dr_inside_full_back_ip",
    "Inside Full-Back",
    "in_possession",
    "full_back",
    ["DL", "DR"],
  ),
  role(
    "dl_dr_playmaking_wing_back_ip",
    "Playmaking Wing-Back",
    "in_possession",
    "full_back",
    ["DL", "DR"],
  ),
  role("dl_dr_full_back_oop", "Full-Back", "out_of_possession", "full_back", [
    "DL",
    "DR",
  ]),
  role(
    "dl_dr_pressing_full_back_oop",
    "Pressing Full-Back",
    "out_of_possession",
    "full_back",
    ["DL", "DR"],
  ),
  role(
    "dl_dr_holding_full_back_oop",
    "Holding Full-Back",
    "out_of_possession",
    "full_back",
    ["DL", "DR"],
  ),
  role(
    "gk_traditional_goalkeeper_ip",
    "Traditional Goalkeeper",
    "in_possession",
    "goalkeeper",
    ["GK"],
  ),
  role(
    "gk_ball_playing_goalkeeper_ip",
    "Ball-Playing Goalkeeper",
    "in_possession",
    "goalkeeper",
    ["GK"],
  ),
  role(
    "gk_no_nonsense_goalkeeper_ip",
    "No-Nonsense Goalkeeper",
    "in_possession",
    "goalkeeper",
    ["GK"],
  ),
  role(
    "gk_traditional_goalkeeper_oop",
    "Traditional Goalkeeper",
    "out_of_possession",
    "goalkeeper",
    ["GK"],
  ),
  role(
    "gk_sweeper_keeper_oop",
    "Sweeper Keeper",
    "out_of_possession",
    "goalkeeper",
    ["GK"],
  ),
  role(
    "gk_line_holding_keeper_oop",
    "Line-Holding Keeper",
    "out_of_possession",
    "goalkeeper",
    ["GK"],
  ),
  role(
    "st_deep_lying_forward_ip",
    "Deep-Lying Forward",
    "in_possession",
    "striker",
    ["ST"],
  ),
  role("st_centre_forward_ip", "Centre Forward", "in_possession", "striker", [
    "ST",
  ]),
  role("st_target_forward_ip", "Target Forward", "in_possession", "striker", [
    "ST",
  ]),
  role("st_poacher_ip", "Poacher", "in_possession", "striker", ["ST"]),
  role("st_channel_forward_ip", "Channel Forward", "in_possession", "striker", [
    "ST",
  ]),
  role("st_false_nine_ip", "False Nine", "in_possession", "striker", ["ST"]),
  role(
    "st_centre_forward_oop",
    "Centre Forward",
    "out_of_possession",
    "striker",
    ["ST"],
  ),
  role(
    "st_tracking_centre_forward_oop",
    "Tracking Centre Forward",
    "out_of_possession",
    "striker",
    ["ST"],
  ),
  role(
    "st_central_outlet_centre_forward_oop",
    "Central Outlet Centre Forward",
    "out_of_possession",
    "striker",
    ["ST"],
  ),
  role(
    "st_splitting_outlet_centre_forward_oop",
    "Splitting Outlet Centre Forward",
    "out_of_possession",
    "striker",
    ["ST"],
  ),
  role(
    "ml_mr_wide_midfielder_ip",
    "Wide Midfielder",
    "in_possession",
    "wide_midfielder",
    ["ML", "MR"],
  ),
  role("ml_mr_winger_ip", "Winger", "in_possession", "wide_midfielder", [
    "ML",
    "MR",
  ]),
  role(
    "ml_mr_playmaking_winger_ip",
    "Playmaking Winger",
    "in_possession",
    "wide_midfielder",
    ["ML", "MR"],
  ),
  role(
    "ml_mr_inside_winger_ip",
    "Inside Winger",
    "in_possession",
    "wide_midfielder",
    ["ML", "MR"],
  ),
  role(
    "ml_mr_wide_midfielder_oop",
    "Wide Midfielder",
    "out_of_possession",
    "wide_midfielder",
    ["ML", "MR"],
  ),
  role(
    "ml_mr_tracking_wide_midfielder_oop",
    "Tracking Wide Midfielder",
    "out_of_possession",
    "wide_midfielder",
    ["ML", "MR"],
  ),
  role(
    "ml_mr_wide_outlet_wide_midfielder_oop",
    "Wide Outlet Wide Midfielder",
    "out_of_possession",
    "wide_midfielder",
    ["ML", "MR"],
  ),
  role("wbl_wbr_wing_back_ip", "Wing-Back", "in_possession", "wing_back", [
    "WBL",
    "WBR",
  ]),
  role(
    "wbl_wbr_advanced_wing_back_ip",
    "Advanced Wing-Back",
    "in_possession",
    "wing_back",
    ["WBL", "WBR"],
  ),
  role(
    "wbl_wbr_inside_wing_back_ip",
    "Inside Wing-Back",
    "in_possession",
    "wing_back",
    ["WBL", "WBR"],
  ),
  role(
    "wbl_wbr_playmaking_wing_back_ip",
    "Playmaking Wing-Back",
    "in_possession",
    "wing_back",
    ["WBL", "WBR"],
  ),
  role("wbl_wbr_wing_back_oop", "Wing-Back", "out_of_possession", "wing_back", [
    "WBL",
    "WBR",
  ]),
  role(
    "wbl_wbr_pressing_wing_back_oop",
    "Pressing Wing-Back",
    "out_of_possession",
    "wing_back",
    ["WBL", "WBR"],
  ),
  role(
    "wbl_wbr_holding_wing_back_oop",
    "Holding Wing-Back",
    "out_of_possession",
    "wing_back",
    ["WBL", "WBR"],
  ),
  role("aml_amr_winger_ip", "Winger", "in_possession", "winger", [
    "AML",
    "AMR",
  ]),
  role(
    "aml_amr_inside_forward_ip",
    "Inside Forward",
    "in_possession",
    "winger",
    ["AML", "AMR"],
  ),
  role(
    "aml_amr_playmaking_winger_ip",
    "Playmaking Winger",
    "in_possession",
    "winger",
    ["AML", "AMR"],
  ),
  role("aml_amr_wide_forward_ip", "Wide Forward", "in_possession", "winger", [
    "AML",
    "AMR",
  ]),
  role("aml_amr_inside_winger_ip", "Inside Winger", "in_possession", "winger", [
    "AML",
    "AMR",
  ]),
  role("aml_amr_winger_oop", "Winger", "out_of_possession", "winger", [
    "AML",
    "AMR",
  ]),
  role(
    "aml_amr_tracking_winger_oop",
    "Tracking Winger",
    "out_of_possession",
    "winger",
    ["AML", "AMR"],
  ),
  role(
    "aml_amr_inside_outlet_winger_oop",
    "Inside Outlet Winger",
    "out_of_possession",
    "winger",
    ["AML", "AMR"],
  ),
  role(
    "aml_amr_wide_outlet_winger_oop",
    "Wide Outlet Winger",
    "out_of_possession",
    "winger",
    ["AML", "AMR"],
  ),
] as const satisfies readonly MoneyballRoleCatalogEntry[];

export type MoneyballRoleId = (typeof MONEYBALL_ROLE_CATALOG)[number]["id"];
