export const DEFAULT_STAFF_TABLE_COLUMN_IDS = [
  "name",
  "age",
  "nationality",
  "ca",
  "pa",
  "role.assistant_manager",
  "role.manager",
  "role.coach_attacking_technical",
  "role.coach_attacking_tactical",
  "role.coach_defending_technical",
  "role.coach_defending_tactical",
  "role.coach_possession_technical",
  "role.coach_possession_tactical",
  "role.coach_fitness",
  "role.coach_goalkeeping",
  "role.set_piece_coach",
  "role.loan_manager",
  "role.head_of_youth_development",
  "role.scout",
  "role.director_of_football",
  "role.technical_director",
  "role.recruitment_analyst",
  "role.head_performance_analyst",
  "role.performance_analyst",
  "role.physio",
  "role.sports_scientist",
] as const;
