/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AcademyRouteImport } from './app/routes/academy'
import { Route as PlannerRouteImport } from './app/routes/planner'
import { Route as SearchRouteImport } from './app/routes/search'
import { Route as StaffRouteImport } from './app/routes/staff'
import { Route as PlayersUidRouteImport } from './app/routes/players.$uid'
import { Route as StaffUidRouteImport } from './app/routes/staff.$uid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersUidRoute = PlayersUidRouteImport.update({
  id: '/players/$uid',
  path: '/players/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffUidRoute = StaffUidRouteImport.update({
  id: '/$uid',
  path: '/$uid',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/planner': typeof PlannerRoute
  '/search': typeof SearchRoute
  '/staff': typeof StaffRouteWithChildren
  '/players/$uid': typeof PlayersUidRoute
  '/staff/$uid': typeof StaffUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/planner': typeof PlannerRoute
  '/search': typeof SearchRoute
  '/staff': typeof StaffRouteWithChildren
  '/players/$uid': typeof PlayersUidRoute
  '/staff/$uid': typeof StaffUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/planner': typeof PlannerRoute
  '/search': typeof SearchRoute
  '/staff': typeof StaffRouteWithChildren
  '/players/$uid': typeof PlayersUidRoute
  '/staff/$uid': typeof StaffUidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/planner'
    | '/search'
    | '/staff'
    | '/players/$uid'
    | '/staff/$uid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/planner'
    | '/search'
    | '/staff'
    | '/players/$uid'
    | '/staff/$uid'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/planner'
    | '/search'
    | '/staff'
    | '/players/$uid'
    | '/staff/$uid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  PlannerRoute: typeof PlannerRoute
  SearchRoute: typeof SearchRoute
  StaffRoute: typeof StaffRouteWithChildren
  PlayersUidRoute: typeof PlayersUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$uid': {
      id: '/players/$uid'
      path: '/players/$uid'
      fullPath: '/players/$uid'
      preLoaderRoute: typeof PlayersUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$uid': {
      id: '/staff/$uid'
      path: '/$uid'
      fullPath: '/staff/$uid'
      preLoaderRoute: typeof StaffUidRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface StaffRouteChildren {
  StaffUidRoute: typeof StaffUidRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffUidRoute: StaffUidRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  PlannerRoute: PlannerRoute,
  SearchRoute: SearchRoute,
  StaffRoute: StaffRouteWithChildren,
  PlayersUidRoute: PlayersUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
